In [124]:
import numpy as np
import pandas as pd
import seaborn as sns

from matplotlib import pyplot as plt

from sklearn.metrics import make_scorer, confusion_matrix, precision_recall_fscore_support, f1_score, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import RepeatedKFold, GridSearchCV, cross_val_score

from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LinearRegression

In [151]:
boston = pd.read_csv('./modified_boston.csv', index_col=0)
boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,11.292897
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,15.113707
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,26.034624
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,29.201223
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,24.099477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,12.242679
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,17.066060
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,11.036473
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,13.672169
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,4.767363

In [110]:
remove_columns = ['chas', 'rad', 'age']
boston_mod = boston
boston_mod.drop(columns=remove_columns, inplace=True)
boston_mod['rm'] = np.square(boston_mod['rm'])
boston_mod['lstat'] = 1/boston_mod['l']
target = 'medv'
X = boston_mod.drop(columns=[target]).to_numpy()
y = boston_mod[target].to_numpy()
rkf = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1234)

pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('knn', KNeighborsRegressor())
])

param_grid = {
    'knn__n_neighbors': [ 1, 2, 6, 10, 17, 31, 54, 96, 170, 300 ]
}
cv = GridSearchCV(pipe, param_grid=param_grid, cv=rkf)
cv.fit(X, y)

best_k = cv.best_params_
best_perf = cv.best_score_
print(best_k)
print(best_perf)

{'knn__n_neighbors': 6}
0.664454138307561

In [152]:
columns = ['crim', 'indus', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat', 'medv']
target = 'medv'
X = boston.drop(columns=[target]).to_numpy()
y = boston[target].to_numpy()
rkf = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1234)
lm_EDA_perf = np.mean(cross_val_score(LinearRegression(), X, y, cv=rkf))
print(lm_EDA_perf)
for column in columns: 
    boston_mod = boston
    boston_mod[column] = np.square(boston_mod[column])
    target = 'medv'
    X = boston_mod.drop(columns=[target]).to_numpy()
    y = boston_mod[target].to_numpy()
    rkf = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1234)
    lm_EDA_perf = np.mean(cross_val_score(LinearRegression(), X, y, cv=rkf))
    print(lm_EDA_perf)

0.4427238340446265
0.4426732112319646
0.44551303981831164
0.44491032745474474
0.4760808263504534
0.475686436059375
0.4642761489589854
0.46390613433029365
0.46100610981625695
0.45993235256180187
0.4596370746472538
0.44366479990910956
0.28448231557668113

In [135]:
boston.column

AttributeError: 'DataFrame' object has no attribute 'column'